/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ActivityItem: typeof import('./components/Dashboard/ActivityItem.vue')['default']
    Appbar: typeof import('./components/Appbar.vue')['default']
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    AvatarStack: typeof import('./components/CourseList/AvatarStack.vue')['default']
    CardQuestionQuiz: typeof import('./components/Lesson/CardQuestionQuiz.vue')['default']
    CardQuizResult: typeof import('./components/Lesson/CardQuizResult.vue')['default']
    Cards: typeof import('./components/CourseList/Cards.vue')['default']
    CourseBanner: typeof import('./components/CourseDetail/CourseBanner.vue')['default']
    CourseDescription: typeof import('./components/CourseDetail/CourseDescription.vue')['default']
    CourseDetails: typeof import('./components/CourseDetail/CourseDetails.vue')['default']
    CourseExercises: typeof import('./components/CourseDetail/CourseExercises.vue')['default']
    CourseImage: typeof import('./components/CourseDetail/CourseImage.vue')['default']
    CourseItem: typeof import('./components/CourseList/CourseItem.vue')['default']
    CourseLessons: typeof import('./components/CourseDetail/CourseLessons.vue')['default']
    CourseListCard: typeof import('./components/Dashboard/CourseListCard.vue')['default']
    CourseMainContent: typeof import('./components/CourseDetail/CourseMainContent.vue')['default']
    CourseProgress: typeof import('./components/CourseDetail/CourseProgress.vue')['default']
    CourseRecommendLessons: typeof import('./components/CourseDetail/CourseRecommendLessons.vue')['default']
    CourseSidebar: typeof import('./components/CourseDetail/CourseSidebar.vue')['default']
    DialogLearningType: typeof import('./components/Lesson/DialogLearningType.vue')['default']
    ErrorAlert: typeof import('./components/ErrorAlert.vue')['default']
    FeedbackCard: typeof import('./components/Dashboard/FeedbackCard.vue')['default']
    FeedbackLesson: typeof import('./components/CourseDetail/FeedbackLesson.vue')['default']
    GetGoalsModal: typeof import('./components/CourseDetail/GetGoalsModal.vue')['default']
    LearningOutcomes: typeof import('./components/CourseList/LearningOutcomes.vue')['default']
    LearningOutcomesModal: typeof import('./components/CourseList/LearningOutcomesModal.vue')['default']
    ProgressStats: typeof import('./components/CourseDetail/ProgressStats.vue')['default']
    RecentActivityCard: typeof import('./components/Dashboard/RecentActivityCard.vue')['default']
    RecentCourses: typeof import('./components/CourseList/RecentCourses.vue')['default']
    RecommendationCard: typeof import('./components/CourseDetail/RecommendationCard.vue')['default']
    RecommendCard: typeof import('./components/CourseDetail/RecommendationCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ShowDocumentsModal: typeof import('./components/CourseDetail/ShowDocumentsModal.vue')['default']
    Sidebar: typeof import('./components/Sidebar.vue')['default']
    SuccessAlert: typeof import('./components/SuccessAlert.vue')['default']
    WelcomeCard: typeof import('./components/Dashboard/WelcomeCard.vue')['default']
  }
}
